from enum import Enum

class AuthMethods(str, Enum):
    otp = "otp"
    google = "google"
    github = "github"
    facebook = "facebook"
    linkedin = "linkedin"
    twitter = "twitter"
    microsoft = "microsoft"
    apple = "apple"
    yahoo = "yahoo"
    discord = "discord"
    slack = "slack"
    twitch = "twitch"
    spotify = "spotify"
    dropbox = "dropbox"
    amazon = "amazon"
    bitbucket = "bitbucket"
    gitlab = "gitlab"
    okta = "okta"
    salesforce = "salesforce"
    shopify = "shopify"
    wordpress = "wordpress"
    zoom = "zoom"
    slack_oauth = "slack_oauth"
    custom_oauth = "custom_oauth"